#!/usr/bin/env python3

from pathlib import Path
import sys

# we make sure we can import runtest and runtest_config
sys.path.append(str(Path(__file__).parents[1]))

# we import essential functions from the runtest library
from runtest import version_info, get_filter, cli, run

# this tells runtest how to run your code
from runtest_config import configure

# we stop the script if the major version is not compatible
assert version_info.major == 2

# construct filter(s)
f = [
    get_filter(from_string='State                (Hartree)             (eV)',
               num_lines=6,
               abs_tolerance=1.0e-4,
               mask=[2]),
    get_filter(from_string='Root  Eigenvalue (Re)   Eigenvalue (Im)    |residual|   Delta E (Re)', # check each iteration
               num_lines=7,                                 
               abs_tolerance=1.0e-4,
               ignore_sign=True,
               mask=[2,3])
]

# invoke the command line interface parser which returns options
options = cli()

ierr = 0
inp = 'ccsd_right_es_energies_imaginary.inp'
# the run function runs the code and filters the outputs
ierr += run(options,
            configure,
            input_files=inp,
            filters={'out': f})

sys.exit(ierr)
