#!/usr/bin/env python3

from pathlib import Path
import sys

# we make sure we can import runtest and runtest_config
sys.path.append(str(Path(__file__).parents[1]))

# we import essential functions from the runtest library
from runtest import version_info, cli, run

# this tells runtest how to run your code
from runtest_config import configure

# functions to get the filters
from filters import get_eom_filter, get_polarizability_filter

# we stop the script if the major version is not compatible
assert version_info.major == 2

# construct filter(s)
n_states = 4
threshold = 1.0e-10
f = get_eom_filter(n_states, threshold)
g = get_polarizability_filter(threshold)

f.extend(g)

# invoke the command line interface parser which returns options
options = cli()

ierr = 0
for inp in ['ccs_lr_polarizability_transition_moments.inp']:
    # the run function runs the code and filters the outputs
    ierr += run(options,
                configure,
                input_files=inp,
                filters={'out': f})

sys.exit(ierr)
