stages:
  - build
  - run

build:
  stage: build
  script:
    - echo "Hello World"
    - git submodule init
    - git submodule update
    - ./setup --int32 -FC=gfortran -CXX=g++-8
    - cd build
    - make -j2
  artifacts:
    paths: 
      - build/

run:
  stage: run
  script:
    - cd build
    - ctest
