stages:
  - build
  - run

build:
  stage: build
  script:
    - whoami
    - cmake --version
    - git submodule init
    - git submodule update
    - ./setup --int32 -FC=gfortran-8 -CXX=g++-8
    - cd build
    - make
  only:
    - master
    - merge_requests
  artifacts:
    paths: 
      - build/

run:
  stage: run
  script:
    - cd build
    - ctest --verbose
    - cat tests/hf_energy/hf_energy.stderr
    - cat tests/hf_energy/hf_energy.stdout
    - cat tests/hf_energy/hf_energy.out
  only:
    - master
    - merge_requests
