image: registry.gitlab.com/et-program/et/ubuntu-for-et-v4

stages:
  - build
  - run

build:
  stage: build
  script:
    - whoami
    - cmake --version
    - git submodule init
    - git submodule update
    - ./setup --int32 -FC=gfortran-8 -CXX=g++-8 --pcm $extra_setup_options
    - cd build
    - make
  tags:
    - docker
  only:
    - master
    - development
    - merge_requests
  artifacts:
    paths: 
      - build/

run:
  stage: run
  script:
    - cd build
    - ctest
  tags:
    - docker
  only:
    - master
    - development
    - merge_requests
