image: registry.gitlab.com/et-program/et/ubuntu-for-et:v5.0

stages:
  - pystyle
  - build
  - run

pystyle:
  stage: pystyle
  image: python:3-buster
  needs: []
  script:
    - pip install black
    - black --check .
  only:
    - master
    - development
    - merge_requests
    - release/1.1

build:
  stage: build
  needs: []
  script:
    - whoami
    - cmake --version
    - git submodule init
    - git submodule update
    - ./setup --int32 -FC=gfortran-8 -CXX=g++-8 --pcm $extra_setup_options
    - cd build
    - make
  tags:
    - docker
  only:
    - master
    - development
    - merge_requests
    - release/1.1
  artifacts:
    paths: 
      - build/

run:
  stage: run
  needs: ["build"]
  script:
    - cd build
    - ctest
  tags:
    - docker
  only:
    - master
    - development
    - merge_requests
    - release/1.1
