image: registry.gitlab.com/et-program/et/alpine-for-et

stages:
  - pystyle
  - build
  - run
  - prepare-release
  - create-release

pystyle:
  stage: pystyle
  image: python:3-buster
  needs: []
  script:
    - pip install black
    - black --check --diff .
  only:
    - master
    - development
    - merge_requests
    - /^release\/\d+\.\d+$/

build:
  stage: build
  needs: []
  script:
    - whoami
    - cmake --version
    - git submodule init
    - git submodule update
    - >
      if [ "$coverage" == "true" ]; then 
        extra_F_flags=' -fprofile-arcs -ftest-coverage'
      fi
    - ./setup.py --int32 --enable-pfunit --pfunit-dir=/pFUnit/build/installed -FC=gfortran -CXX=g++ -F-flags="$extra_F_flags" $extra_setup_options --pcm
    - cd build
    - cmake_command=$(cat setup_cmake_output | head -1)
    - echo ${cmake_command}
    - make
  tags:
    - docker
  only:
    - master
    - development
    - merge_requests
    - /^release\/\d+\.\d+$/
  artifacts:
    paths: 
      - build/

run:
  stage: run
  needs: ["build"]
  parallel: 15
  script:
    - cd build
    - echo I am node $CI_NODE_INDEX out of a total of $CI_NODE_TOTAL nodes
    # get line that contains the number of tests
    - n_tests_total=$(ctest -N | tail -1)     
    # extract total number of tests from the line
    - n_tests_total=${n_tests_total//[^0-9]/} 
    - echo There are a total of $n_tests_total tests  
    - n_tests=$(expr $n_tests_total / $CI_NODE_TOTAL)
    - first_test=$(expr \( $CI_NODE_INDEX - 1 \) \* $n_tests + 1)
    - last_test_in_batch=$(expr $first_test + $n_tests - 1)
    # if (last node) => last_test = n_tests_total
    # else           => last_test = last_test_in_batch
    - last_test=$(($CI_NODE_INDEX==$CI_NODE_TOTAL?$n_tests_total:$last_test_in_batch))
    - echo Will run test $first_test to test $last_test 
    - ctest -I $first_test,$last_test --output-on-failure
    - >
      if [ "$coverage" == "true" ]; then 
        curl https://keybase.io/codecovsecurity/pgp_keys.asc | gpg --import # One-time step
        curl -Os https://uploader.codecov.io/latest/alpine/codecov
        curl -Os https://uploader.codecov.io/latest/alpine/codecov.SHA256SUM
        curl -Os https://uploader.codecov.io/latest/alpine/codecov.SHA256SUM.sig
        gpg --verify codecov.SHA256SUM.sig codecov.SHA256SUM
        sha256sum -c codecov.SHA256SUM
        chmod +x codecov
        ./codecov -t ${CODECOV_TOKEN}
      fi
  tags:
    - docker
  only:
    - master
    - development
    - merge_requests
    - /^release\/\d+\.\d+$/

prepare-release:
  stage: prepare-release
  image: python:latest
  script:
    - python3 dev_tools/export_release_info.py 
  artifacts:
    paths:
      - major.txt
      - minor.txt
      - patch.txt   
      - description.txt
  rules:
    - if: '$CI_PROJECT_NAMESPACE == "eT-program" && $CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'
      when: on_success
    - when: never # Default: never run if the above conditions are false

create-release:
  stage: create-release
  image: registry.gitlab.com/gitlab-org/release-cli
  needs: ["prepare-release"]
  script: 
    - major=$(cat major.txt)
    - minor=$(cat minor.txt)
    - patch=$(cat patch.txt)
    - description=$(cat description.txt)
    - >
      release-cli create 
      --name "v${major}.${minor}.${patch}" 
      --description "${description}"
      --tag-name "v${major}.${minor}.${patch}" 
      --ref $CI_COMMIT_SHA
  rules:
    - if: '$CI_PROJECT_NAMESPACE == "eT-program" && $CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"'
      when: on_success
    - when: never # Default: never run if the above conditions are false

