stages:
  - build
  - run

build:
  stage: build
  script:
    - gfortran --version
    - g++ --version
    - git submodule init
    - git submodule update
    - ./setup -FC=gfortran -CXX=g++-8
    - cd build
    - make
  artifacts:
    paths: 
      - build/

run:
  stage: run
  script:
    - cd build
    - ctest
