stages:
  - build
  - run

build:
  stage: build
  script:
    - ./setup --int32 -FC=gfortran -CXX=g++-8
    - cd build
    - make
  artifacts:
    - /build

run:
  stage: run
  script:
    - cd build
    - ctest