stages:
  - build
  - run

build:
  stage: build
  script:
    - echo "Compiling eT"
    - whoami
    - gfortran --version
    - g++ --version
    - cmake --version
    - git submodule init
    - git submodule update
    - ./setup --int32 -FC=gfortran -CXX=g++
    - cd build
    - make -j2
  artifacts:
    paths: 
      - build/

run:
  stage: run
  script:
    - echo "Running eT tests"
    - cd build
    - ctest
  only:
    - master
