stages:
  - build
  - run

build:
  stage: build
  script:
    - whoami
    - gfortran-8 --version
    - g++-8 --version
    - cmake --version
    - git submodule init
    - git submodule update
    - ./setup --int32 -FC=gfortran-8 -CXX=g++-8
    - cd build
    - make -j2
  only:
    - master
    - merge_requests
  artifacts:
    paths: 
      - build/

run:
  stage: run
  script:
    - cd build
    - ctest
  only:
    - master
    - merge_requests
