stages:
  - build
  - run

build:
  stage: build
  script:
    - whoami
    - gfortran --version
    - g++ --version
    - cmake --version
    - git submodule init
    - git submodule update
    - ./setup --int32 -FC=gfortran -CXX=g++
    - cd build
    - make
  artifacts:
    paths: 
      - build/

run:
  stage: run
  script:
    - cd build
    - ctest --verbose
