index_packed – The eT program
index_packed Function
5 statements
Source File
public function index_packed(i, j)
Packed index
Written by Eirik F. Kjønstad and Sarai D. Folkestad, Jan 2017
Calculates the packed index of symetric matrix.
Arguments
Type Intent Optional Attributes Name
integer(kind=i15), intent(in) :: i
integer(kind=i15), intent(in) :: j
Return Value integer(kind=i15)
Called By
All Procedures
alloc_int_memory_manager alloc_memory_manager allocator allocator_int analyze_double_excitation_vector_cc2 analyze_double_excitation_vector_ccsd analyze_double_excitation_vector_mlcc2 analyze_single_excitation_vector_ccs batch_limits calc_ampeqs_ccs calc_ampeqs_norm_ccs calc_ampeqs_norm_ccsd calc_ampeqs_norm_mlccsd calc_energy_cc2 calc_energy_ccs calc_energy_ccsd calc_energy_correction_ccsdpt calc_energy_mlcc2 calc_energy_mlccsd calc_energy_mp2 calc_quasi_Newton_doubles_ccsd calc_quasi_Newton_doubles_mlccsd calc_quasi_Newton_singles_ccs calc_triples_cc3 calculate_orbital_differences_cc2 calculate_orbital_differences_ccs calculate_orbital_differences_ccsd calculate_orbital_differences_mlcc2 calculation_reader_ccs cc2_cnto_lower_level_method_mlcc2 cc2_cnto_orbitals_mlcc2 ccsd_cnto_lower_level_method_mlccsd ccsd_cnto_orbitals_mlccsd check_orthogonality cholesky_decomposition_mlcc2 cholesky_localization_CCSD_CC2_CCS_mlccsd cholesky_localization_CCSD_CC2_mlccsd cholesky_localization_CCSD_CCS_mlccsd cholesky_localization_drv_mlcc2 cholesky_localization_drv_mlccsd cholesky_orbital_constructor_mlcc2 cholesky_orbitals_mlcc2 cnto_orbital_drv_mlcc2 cnto_orbital_drv_mlccsd construct_active_ao_index_list construct_ao_fock_hf construct_ao_fock_new_hf construct_density_matrices_hf construct_density_matrix_hf construct_density_matrix_v_hf construct_eta_ccs construct_eta_ccsd construct_fock_ccs construct_gradient_vector_ccs construct_MO_transformation_matrix_mlccsd construct_next_response_trial_vectors_ccs construct_next_trial_vectors_ccs construct_omega_cc2 construct_omega_cc3 construct_omega_ccs construct_omega_ccsd construct_omega_ccsdpt construct_omega_mlcc2 construct_omega_mlccsd construct_orbital_coef_CC2_CCS_mlccsd construct_orbital_energy_CC2_CCS_mlccsd construct_perturbative_doubles_ccsd construct_perturbative_doubles_mlccsd construct_reduced_gradient_ccs construct_reduced_matrix_ccs core_ionization_jacobian_ccsd_transformation_ccsd cvs_jacobian_ccsd_transformation_ccsd cvs_residual_projection_cc2 cvs_residual_projection_ccs cvs_residual_projection_ccsd cvs_residual_projection_mlcc2 cvs_rho_a_i_projection_ccs cvs_rho_aibj_projection_cc2 cvs_rho_aibj_projection_ccsd cvs_rho_aibj_projection_mlcc2 dealloc_int_memory_manager dealloc_memory_manager deallocator deallocator_int destruct_amplitudes_ccs destruct_amplitudes_ccsd destruct_amplitudes_mlccsd destruct_double_amplitudes_mlccsd destruct_ground_state_ccs destruct_ground_state_ccsdpt destruct_omega_ccs destruct_omega_ccsd destruct_orbital_coef_CC2_CCS_mlccsd destruct_orbital_energy_CC2_CCS_mlccsd destruct_s2am_cc2 destruct_x2am_mlcc2 determine_limits_batching_index diis_ccs drv_ccs drv_hf drv_mp2 excited_state_cleanup_ccs excited_state_driver_ccs excited_state_preparations_cc2 excited_state_preparations_ccs excited_state_preparations_ccsd excited_state_preparations_mlcc2 excited_state_solver_ccs find_core_mo_ccs find_start_trial_indices_ccs find_start_trial_indices_core_ccs general_specs_reader_ccs generate_unit_identifier get_available get_CC2_active_indices_mlcc2 get_CC2_active_indices_mlccsd get_CC2_n_active_mlcc2 get_CC2_n_active_mlccsd get_CCSD_active_indices_mlccsd get_CCSD_n_active_mlccsd get_cholesky_ab_ccs get_cholesky_ai_ccs get_cholesky_ai_for_cc2_amplitudes_mlccsd get_cholesky_ia_ccs get_cholesky_ij_ccs get_mlccsd_x2am_mlccsd get_n_lowest get_oo_oo_ccs get_oo_oo_electronic_repulsion_ccs get_oo_ov_ccs get_oo_ov_electronic_repulsion_ccs get_oo_vo_ccs get_oo_vo_electronic_repulsion_ccs get_oo_vv_ccs get_oo_vv_electronic_repulsion_ccs get_ov_oo_ccs get_ov_oo_electronic_repulsion_ccs get_ov_ov_ccs get_ov_ov_electronic_repulsion_ccs get_ov_vo_ccs get_ov_vo_electronic_repulsion_ccs get_ov_vv_ccs get_ov_vv_electronic_repulsion_ccs get_s2am_cc2 get_s2am_mlcc2 get_vo_oo_ccs get_vo_oo_electronic_repulsion_ccs get_vo_ov_ccs get_vo_ov_electronic_repulsion_ccs get_vo_vo_ccs get_vo_vo_electronic_repulsion_ccs get_vo_vv_ccs get_vo_vv_electronic_repulsion_ccs get_vv_oo_ccs get_vv_oo_electronic_repulsion_ccs get_vv_ov_ccs get_vv_ov_electronic_repulsion_ccs get_vv_vo_ccs get_vv_vo_electronic_repulsion_ccs get_vv_vv_ccs get_vv_vv_electronic_repulsion_ccs ground_state_cleanup_ccs ground_state_driver_ccs ground_state_preparations_ccs ground_state_preparations_ccsd ground_state_solver_ccs index_packed index_three index_two init_batching_index init_cc2 init_cc3 init_ccs init_ccsd init_ccsdpt init_hf init_memory_manager init_mlcc2 init_mlccsd init_mp2 initialize_amplitudes_ccs initialize_amplitudes_ccsd initialize_amplitudes_mlccsd initialize_excited_states_cc2 initialize_excited_states_ccs initialize_excited_states_mlcc2 initialize_excited_states_mlccsd initialize_fock_matrix_ccs initialize_ground_state_ccs initialize_ground_state_ccsd initialize_ground_state_mlccsd initialize_omega_ccs initialize_omega_ccsd initialize_omega_mlccsd initialize_response_ccs initialize_trial_vectors_ccs initialize_trial_vectors_core_ccs initialize_trial_vectors_core_ionization_ccs initialize_trial_vectors_valence_ccs initialize_trial_vectors_valence_ionization_ccs ionization_jacobian_ccsd_transformation_ccsd ionization_residual_projection_ccs ionization_residual_projection_ccsd ionization_rho_a_i_projection_ccs ionization_rho_aibj_projection_ccsd ionized_state_driver_ccs jacobi_test_ccs jacobi_test_ccsd jacobian_cc2_a1_cc2 jacobian_cc2_a2_cc2 jacobian_cc2_b1_cc2 jacobian_cc2_b2_cc2 jacobian_cc2_transformation_cc2 jacobian_ccs_a1_ccs jacobian_ccs_b1_ccs jacobian_ccs_transformation_ccs jacobian_ccsd_a1_ccsd jacobian_ccsd_a2_ccsd jacobian_ccsd_b1_ccsd jacobian_ccsd_b2_ccsd jacobian_ccsd_c1_ccsd jacobian_ccsd_c2_ccsd jacobian_ccsd_d1_ccsd jacobian_ccsd_d2_ccsd jacobian_ccsd_e2_ccsd jacobian_ccsd_f2_ccsd jacobian_ccsd_g2_ccsd jacobian_ccsd_h2_ccsd jacobian_ccsd_i2_ccsd jacobian_ccsd_j2_ccsd jacobian_ccsd_k2_ccsd jacobian_ccsd_transformation_ccsd jacobian_mlcc2_a1_mlcc2 jacobian_mlcc2_a2_mlcc2 jacobian_mlcc2_b1_mlcc2 jacobian_mlcc2_b2_mlcc2 jacobian_mlcc2_transformation_mlcc2 jacobian_mlccsd_b2_mlccsd jacobian_mlccsd_c2_mlccsd jacobian_mlccsd_d2_mlccsd jacobian_mlccsd_e2_mlccsd jacobian_mlccsd_f2_mlccsd jacobian_mlccsd_g2_mlccsd jacobian_mlccsd_h2_mlccsd jacobian_mlccsd_i2_mlccsd jacobian_mlccsd_j2_mlccsd jacobian_mlccsd_k2_mlccsd jacobian_mlccsd_transformation_mlccsd jacobian_transpose_ccs_a1_ccs jacobian_transpose_ccs_b1_ccs jacobian_transpose_ccs_transformation_ccs jacobian_transpose_ccsd_a1_ccsd jacobian_transpose_ccsd_a2_ccsd jacobian_transpose_ccsd_b1_ccsd jacobian_transpose_ccsd_b2_ccsd jacobian_transpose_ccsd_c1_ccsd jacobian_transpose_ccsd_c2_ccsd jacobian_transpose_ccsd_d1_ccsd jacobian_transpose_ccsd_d2_ccsd jacobian_transpose_ccsd_e1_ccsd jacobian_transpose_ccsd_e2_ccsd jacobian_transpose_ccsd_f1_ccsd jacobian_transpose_ccsd_f2_ccsd jacobian_transpose_ccsd_g1_ccsd jacobian_transpose_ccsd_g2_ccsd jacobian_transpose_ccsd_h2_ccsd jacobian_transpose_ccsd_i2_ccsd jacobian_transpose_ccsd_transformation_ccsd method_reader mlcc_reader_mlcc2 mlcc_reader_mlccsd new_amplitudes_ccs new_amplitudes_ccsd new_amplitudes_mlccsd num_batch num_batch_memory_manager num_two_batch num_two_batch_memory_manager omega_cc2_a1_cc2 omega_cc2_b1_cc2 omega_cc3_a1_cc3 omega_cc3_a2_cc3 omega_cc3_b2_cc3 omega_ccs_a1_ccs omega_ccsd_a1_ccsd omega_ccsd_a2_ccsd omega_ccsd_b1_ccsd omega_ccsd_b2_ccsd omega_ccsd_c1_ccsd omega_ccsd_c2_ccsd omega_ccsd_d2_ccsd omega_ccsd_e2_ccsd omega_integrals_cc3 omega_mlcc2_a1_mlcc2 omega_mlcc2_b1_mlcc2 omega_mlccsd_a1_mlccsd omega_mlccsd_a2_mlccsd omega_mlccsd_b1_mlccsd omega_mlccsd_b2_mlccsd omega_mlccsd_c2_mlccsd omega_mlccsd_d2_mlccsd omega_mlccsd_e2_mlccsd one_electron_t1_ccs orbital_partitioning_mlcc2 orbital_partitioning_mlccsd orbital_reader_mlcc_orb packed_size packin precondition_residual_ccs precondition_residual_core_ccs precondition_residual_core_ionization_ccs precondition_residual_valence_ccs precondition_residual_valence_ionization_ccs print_excitation_vector_ccs print_excitation_vector_ccsd print_excitation_vector_mlcc2 print_excitation_vector_mlccsd print_excited_state_info_ccs print_orbital_info_mlcc2 print_orbital_info_mlccsd read_amplitudes_cc2 read_amplitudes_ccs read_amplitudes_ccsd read_amplitudes_mlcc2 read_amplitudes_mlccsd read_atom_info read_cc2_double_amplitudes_cc2 read_cc2_double_amplitudes_mlcc2 read_center_info read_cholesky_ab_for_cc2_amplitudes_mlccsd read_cholesky_ab_hf read_cholesky_ai_for_cc2_amplitudes_mlccsd read_cholesky_ai_hf read_cholesky_ia_for_cc2_amplitudes_mlccsd read_cholesky_ia_hf read_cholesky_ij_for_cc2_amplitudes_mlccsd read_cholesky_ij_hf read_double_amplitudes_ccsd read_double_amplitudes_mlccsd read_excited_state_specs_ccs read_ground_state_specs_ccs read_hf_info_hf read_mlccsd_double_amplitudes_mlccsd read_orbital_info_mlcc2 read_orbital_info_mlccsd read_property_specs_ccs read_single_amplitudes_ccs read_t1_vo_ov_electronic_repulsion_ccs read_t1_vv_ov_electronic_repulsion_ccs read_t1_vv_vo_electronic_repulsion_ccs read_t1_vv_vv_electronic_repulsion_ccs read_transform_cholesky_for_CC2_amplitude_mlccsd read_transform_cholesky_hf read_vv_vv_electronic_repulsion_ccs remove_preceding_blanks response_driver_ccs response_preparations_ccs response_solver_ccs save_amplitudes_cc2 save_amplitudes_ccs save_amplitudes_ccsd save_amplitudes_mlcc2 save_amplitudes_mlccsd solve_reduced_eigenvalue_equation_ccs solve_reduced_response_equation_ccs squareup squareup_to_compound store_t1_vo_ov_electronic_repulsion_ccs store_t1_vv_ov_electronic_repulsion_ccs store_t1_vv_vo_electronic_repulsion_ccs store_t1_vv_vv_electronic_repulsion_ccs store_vv_vv_electronic_repulsion_ccs summary_excited_state_info_cc2 summary_excited_state_info_ccs summary_excited_state_info_ccsd summary_excited_state_info_mlcc2 summary_excited_state_info_mlccsd t1_transform_vv_vv_ccs transform_trial_vectors_cc2 transform_trial_vectors_ccs transform_trial_vectors_ccsd transform_trial_vectors_mlcc2 transform_trial_vectors_mlccsd trial_vectors_from_stored_solutions_ccs vec_print vec_print_nonzero_elm work_init
Call graph
calc_energy_ccsd calls index_packed
squareup_to_compound calls index_packed
save_amplitudes_mlccsd calls index_packed
jacobi_test_ccsd calls index_packed
construct_eta_ccsd calls index_packed
read_cholesky_ab_hf calls index_packed
construct_perturbative_doubles_ccsd calls index_packed
read_cholesky_ij_hf calls index_packed
calc_energy_cc2 calls index_packed
calc_energy_correction_ccsdpt calls index_packed
save_amplitudes_cc2 calls index_packed
packin calls index_packed
read_transform_cholesky_hf calls index_packed, squareup
construct_ao_fock_hf calls index_packed, squareup
save_amplitudes_mlcc2 calls index_packed
construct_perturbative_doubles_mlccsd calls index_packed
squareup calls index_packed
construct_ao_fock_new_hf calls squareup