#!/usr/bin/env python3

from pathlib import Path
import sys

# we make sure we can import runtest and runtest_config
sys.path.append(str(Path(__file__).parents[1]))

# we import essential functions from the runtest library
from runtest import version_info, cli, run

# this tells runtest how to run your code
from runtest_config import configure

# functions to get the filters
from filters import get_td_filter, get_file_filter

# we stop the script if the major version is not compatible
assert version_info.major == 2

# construct filter(s)
threshold = 1.0e-8

f = get_td_filter(threshold)
g = get_file_filter(threshold)
filters = {
    'out' : f,
    'cc_propagation_dipole_moment.out' : g,
    'cc_propagation_energy.out' : g,
    'cc_propagation_density_matrix_real.out' : g,
    'cc_propagation_density_matrix_imag.out' : g,
    }

# Add all cube files in result/ to filters dict
result_dir = Path(__file__).parent / "result"
for cube in result_dir.glob("*.cube"):
    cube_suffix = "".join(cube.suffixes)
    filters[cube_suffix.lstrip('.')] = g


# invoke the command line interface parser which returns options
options = cli()

ierr = 0
inp = 'ccsd_td_rk4.inp'
# the run function runs the code and filters the outputs
ierr += run(options,
            configure,
            input_files=inp,
            filters=filters)
sys.exit(ierr)
