#!/usr/bin/env python3

from pathlib import Path
import sys

# we make sure we can import runtest and runtest_config
sys.path.append(str(Path(__file__).parents[1]))

# we import essential functions from the runtest library
from runtest import version_info, get_filter, cli, run

# this tells runtest how to run your code
from runtest_config import configure

# functions to get the filters
from filters import get_hf_filter

# we stop the script if the major version is not compatible
assert version_info.major == 2

# construct filter(s)
n_states = 3
tolerance = 1.0e-8
f = get_hf_filter(tolerance)

# Don't test largest amplitudes as the order of the states can change due to degeneracies
g = [
    get_filter(string="Final ground state energy (a.u.):", abs_tolerance=tolerance),
    get_filter(
        from_string="State                (Hartree)             (eV)",
        num_lines=2 + n_states,
        abs_tolerance=tolerance,
        mask=[2],
    )
]

f.extend(g)


# invoke the command line interface parser which returns options
options = cli()

ierr = 0
inp = 'ccsd_frozen_core_xenon.inp'
# the run function runs the code and filters the outputs
ierr += run(options,
            configure,
            input_files=inp,
            filters={'out': f})

sys.exit(ierr)
