#!/usr/bin/env python3

from pathlib import Path
import sys

# we make sure we can import runtest and runtest_config
sys.path.append(str(Path(__file__).parents[1]))

# we import essential functions from the runtest library
from runtest import version_info, get_filter, cli, run

# this tells runtest how to run your code
from runtest_config import configure

# we stop the script if the major version is not compatible
assert version_info.major == 2

# construct filter(s)
f = [
    get_filter(string='<< mu_x, mu_x >>(0.20E-01):',
               abs_tolerance=1.0e-10),
    get_filter(string='<< mu_z, mu_x >>(0.20E-01):',
               abs_tolerance=1.0e-10),
    get_filter(string='<< mu_x, mu_x >>(0.40E-01):',
               abs_tolerance=1.0e-10),
    get_filter(string='<< mu_z, mu_x >>(0.40E-01):',
               abs_tolerance=1.0e-10),
    get_filter(string='<< mu_x, mu_x >>(0.60E-01):',
               abs_tolerance=1.0e-10),
    get_filter(string='<< mu_z, mu_x >>(0.60E-01):',
               abs_tolerance=1.0e-10),
    get_filter(string='Final ground state energy (a.u.):',
               abs_tolerance=1.0e-10)
]

# invoke the command line interface parser which returns options
options = cli()

ierr = 0
for inp in ['ccsd_eom_polarizability.inp']:
    # the run function runs the code and filters the outputs
    ierr += run(options,
                configure,
                input_files=inp,
                filters={'out': f})

sys.exit(ierr)
