#!/usr/bin/env python3

from pathlib import Path
import sys

# we make sure we can import runtest and runtest_config
sys.path.append(str(Path(__file__).parents[1]))

# we import essential functions from the runtest library
from runtest import version_info, cli, run

# this tells runtest how to run your code
from runtest_config import configure

# functions to get the filters
from filters import get_lanczos_filter, get_file_filter

# we stop the script if the major version is not compatible
assert version_info.major == 2

# construct filter(s)
f1 = get_lanczos_filter(tolerance=1.0e-10)
g = get_file_filter(tolerance=1.0e-7)

filters30 = {'out' : f1}
filters30.update({f'lanczos30_{component}' : g for component in "XYZ"})

f2 = get_lanczos_filter(tolerance=1.0e-10, restart=True)
filters60 = {'out' : f2}
filters60.update({f'lanczos60_{component}' : g for component in "XYZ"})

# invoke the command line interface parser which returns options
options = cli()

ierr = 0
inp = 'ccsd_lanczos_cl30.inp'
# the run function runs the code and filters the outputs
ierr += run(options,
            configure,
            input_files=inp,
            extra_args='-save .',
            filters=filters30)

inp = 'ccsd_lanczos_cl60.inp'
ierr += run(options,
            configure,
            input_files=inp,
            extra_args='-load ccsd_lanczos_cl30_restart_files',
            filters=filters60)

sys.exit(ierr)
