#!/usr/bin/env python3

from pathlib import Path
import sys

# we make sure we can import runtest and runtest_config
sys.path.append(str(Path(__file__).parents[1]))

# we import essential functions from the runtest library
from runtest import version_info, cli, run

# this tells runtest how to run your code
from runtest_config import configure

# functions to get the filters
from filters import get_es_filter

# we stop the script if the major version is not compatible
assert version_info.major == 2

# construct filter(s)
n_states = 6
threshold = 1.0e-10
restart=True
f = get_es_filter(n_states, threshold, restart=restart)

# invoke the command line interface parser which returns options
options = cli()

run(options, configure,
    input_files='cc3_5_micro_iterations.inp',
    extra_args='-save ./')

ierr = 0
for inp in ['restart_cc3_nonlin_davidson.inp']:
    # the run function runs the code and filters the outputs
    ierr += run(options,
                configure,
                input_files=inp,
                extra_args='-load cc3_5_micro_iterations_restart_files',
                filters={'out': f})

sys.exit(ierr)
