eT_program – The eT program
eT_program Program
69 statements
Source File
Uses:
input_output
input_reader
hf_class
mp2_class
ccs_class
cc2_class
ccsd_class
cc3_class
ccsdpt_class
mlcc2_class
mlccsd_class
                    eT - a coupled cluster program
     Written by Eirik F. Kjønstad and Sarai D. Folkestad, May 2017
Calls
Variables
mp2_wf ccs_wf cc2_wf ccsd_wf cc3_wf ccsdpt_wf mlcc2_wf mlccsd_wf wf method unit_input orbital_level
Variables
Type Attributes Name Initial
type(mp2), allocatable, target :: mp2_wf
type(ccs), allocatable, target :: ccs_wf
type(cc2), allocatable, target :: cc2_wf
type(ccsd), allocatable, target :: ccsd_wf
type(cc3), allocatable, target :: cc3_wf
type(ccsdpt), allocatable, target :: ccsdpt_wf
type(mlcc2), allocatable, target :: mlcc2_wf
type(mlccsd), allocatable, target :: mlccsd_wf
class(hf), pointer :: wf => null()
character(len=40) :: method
integer(kind=i15) :: unit_input = -1
character(len=13) :: orbital_level
All Programs
eT_program
Call graph
et_program calls work_init, generate_unit_identifier, method_reader
method_reader calls remove_preceding_blanks