#!/usr/bin/env python3

from pathlib import Path
import sys

# we make sure we can import runtest and runtest_config
sys.path.append(str(Path(__file__).parents[1]))

# we import essential functions from the runtest library
from runtest import version_info, cli, run

# this tells runtest how to run your code
from runtest_config import configure

# functions to get the filters
from filters import get_file_filter, get_es_filter

# we stop the script if the major version is not compatible
assert version_info.major == 2

# construct filter(s)
n_states = 1
threshold = 1.0e-9

f = get_file_filter(threshold)
g = get_es_filter(n_states, threshold)

# invoke the command line interface parser which returns options
options = cli()

ierr = 0
for inp in ["plot_ntos_ccs.inp"]:
    # the run function runs the code and filters the outputs
    ierr += run(options, configure,
                input_files=inp,
                filters={"r_001_nto_v_001.cube": f,
                         "r_001_nto_o_001.cube": f,
                         "out": g})

sys.exit(ierr)
