#!/usr/bin/env python3

from pathlib import Path
import sys

# we make sure we can import runtest and runtest_config
sys.path.append(str(Path(__file__).parents[1]))

# we import essential functions from the runtest library
from runtest import version_info, cli, run

# this tells runtest how to run your code
from runtest_config import configure

# functions to get the filters
from filters import get_hf_filter, get_spin_filter

# we stop the script if the major version is not compatible
assert version_info.major == 2

# invoke the command line interface parser which returns options
options = cli()

ierr = 0

# construct filter(s)
threshold = 1.0e-10
f = get_hf_filter(threshold, convergence=True, restart=True)

g = get_spin_filter(threshold)
f.extend(g)

inp = 'restart_uhf_v1.0.inp'
# the run function runs the code and filters the outputs
ierr += run(options,
            configure,
            input_files=inp,
            extra_args='-load-v1-0 ./old_restart_files',
            filters={'out': f})

sys.exit(ierr)
