#!/usr/bin/env python3

from pathlib import Path
import sys

# we make sure we can import runtest and runtest_config
sys.path.append(str(Path(__file__).parents[1]))

# we import essential functions from the runtest library
from runtest import version_info, cli, run

# this tells runtest how to run your code
from runtest_config import configure

# functions to get the filters
from filters import get_hf_filter, get_spin_filter

# we stop the script if the major version is not compatible
assert version_info.major == 2

# construct filter(s)
threshold = 1.0e-10
spin_threshold = 1.0e-8

f = get_hf_filter(threshold)
f += get_spin_filter(spin_threshold)

# invoke the command line interface parser which returns options
options = cli()

test_dir = Path(__file__).parent
checkfile = test_dir / "uhf_mo_information.out"

ierr = 0
for inp in ['uhf.inp']:
    # the run function runs the code and filters the outputs
    ierr += run(options,
                configure,
                input_files=inp,
                extra_args='-xyz',
                filters={'out': f})

if checkfile.exists():
    filerror = 0
else:
    print(f"Missing file: {checkfile.name}")
    filerror = 1

sys.exit(ierr + filerror)
