#!/usr/bin/env python3

from pathlib import Path
import sys

# we make sure we can import runtest and runtest_config
sys.path.append(str(Path(__file__).parents[1]))

# we import essential functions from the runtest library
from runtest import version_info, cli, run

# this tells runtest how to run your code
from runtest_config import configure

# functions to get the filters
from filters import get_lanczos_filter, get_file_filter

# we stop the script if the major version is not compatible
assert version_info.major == 2

# construct filter(s)
f = get_lanczos_filter(tolerance=1.0e-10)
g = get_file_filter(tolerance=1.0e-7)

filters = {'out' : f}
filters.update({f'lanczos30_{component}' : g for component in "XYZ"})

# invoke the command line interface parser which returns options
options = cli()

ierr = 0
inp = 'ccsd_cvs_lanczos.inp'
# the run function runs the code and filters the outputs
ierr += run(options,
            configure,
            input_files=inp,
            filters=filters)

sys.exit(ierr)
