#!/usr/bin/env python3

from pathlib import Path
import sys

# we make sure we can import runtest and runtest_config
sys.path.append(str(Path(__file__).parents[1]))

# we import essential functions from the runtest library
from runtest import version_info, get_filter, cli, run

# this tells runtest how to run your code
from runtest_config import configure

# we stop the script if the major version is not compatible
assert version_info.major == 2

# construct filter(s)
#
# cannot check transition dipole moment as the states can change in every run
#
f = [
    get_filter(from_string='State                (Hartree)             (eV)',
               num_lines=6,
               abs_tolerance=1.0e-10,
               mask=[2]),
    get_filter(string='Oscillator strength:',
               abs_tolerance=1.0e-10),
    get_filter(string='Final ground state energy (a.u.):',
               abs_tolerance=1.0e-10)
]

# invoke the command line interface parser which returns options
options = cli()

ierr = 0
for inp in ['ccsd_cvs_eom_degeneracy.inp']:
    # the run function runs the code and filters the outputs
    ierr += run(options,
                configure,
                input_files=inp,
                filters={'out': f})

sys.exit(ierr)
