set(eT_CXX_sources
   src/integrals/libint/utils.cpp
   src/integrals/libint/h_xy.cpp
   src/integrals/libint/s_xy.cpp
   src/integrals/libint/g_wxyz.cpp
   src/integrals/libint/L_wxyz.cpp
   src/integrals/libint/libint_initialization.cpp
   src/molecular_system/libint/atom_init.cpp
)
