#
#
#   eT - a coupled cluster program
#   Copyright (C) 2016-2020 the authors of eT
#
#   eT is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   eT is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <https://www.gnu.org/licenses/>.
#
#
set(eT_fortran_sources
   src/eT_program.F90
#
   src/engines/abstract_engine_class.F90
   src/engines/reference_engine_class.F90
   src/engines/hf_geoopt_engine_class.F90
   src/engines/gs_engine_class.F90
   src/engines/es_engine_class.F90
   src/engines/mean_value_engine_class.F90
   src/engines/response_engine_class.F90
   src/engines/td_engine_class.F90
#
   src/integrals/mo_integral_tool_class.F90
#
   src/io/abstract_file_class.F90
   src/io/abstract_out_file_class.F90
   src/io/abstract_other_file_class.F90
   src/io/direct_file_class.F90
   src/io/sequential_file_class.F90
   src/io/input_file_class.F90
   src/io/section_class.F90
   src/io/output_file_class.F90
   src/io/io_utilities.F90
   src/io/global_out.F90
   src/io/global_in.F90
#
   src/libint/libint_initialization.F90
#
   src/memory/batching_index_class.F90
   src/memory/memory_manager_class.F90
#
   src/molecule/atomic_class.F90
   src/molecule/molecular_system/molecular_system_class.F90
   src/molecule/mm_class.F90
   src/molecule/pcm_class.F90
   src/molecule/molecular_system/ao_integrals.F90
   src/molecule/periodic_table.F90
   src/molecule/shell_class.F90
   src/molecule/active_atoms_class.F90
#
   src/solver_tools/cholesky_array_list_class.F90
   src/solver_tools/bfgs_tool_class.F90
   src/solver_tools/diis_tool_class.F90
   src/solver_tools/davidson_tool_class.F90
   src/solver_tools/eigen_davidson_tool_class.F90
   src/solver_tools/linear_davidson_tool_class.F90
   src/solver_tools/es_start_vectors/es_start_vector_tool_class.F90
   src/solver_tools/es_start_vectors/es_valence_start_vector_tool_class.F90
   src/solver_tools/es_start_vectors/es_cvs_start_vector_tool_class.F90
   src/solver_tools/es_start_vectors/es_ip_start_vector_tool_class.F90
   src/solver_tools/es_projectors/es_projection_tool_class.F90
   src/solver_tools/es_projectors/es_cvs_projection_tool_class.F90
   src/solver_tools/es_projectors/es_valence_projection_tool_class.F90
   src/solver_tools/es_projectors/es_ip_projection_tool_class.F90
   src/fields/electric_field_class.F90
   src/solver_tools/precondition_tool_class.F90
   src/solver_tools/asymmetric_lanczos_tool_class.F90
#
   src/solvers/hf/abstract_hf_solver_class.F90
   src/solvers/hf/scf_diis_hf_class.F90
   src/solvers/hf/mo_scf_diis_class.F90
   src/solvers/hf/scf_hf_class.F90
   src/solvers/hf/bfgs_geoopt_hf_class.F90
   src/solvers/cc/diis_cc_gs_class.F90
   src/solvers/cc/diis_cc_es_class.F90
   src/solvers/cc/diis_cc_multipliers_class.F90
   src/solvers/cc/davidson_cc_multipliers_class.F90
   src/solvers/cc/davidson_cc_linear_equations_class.F90
   src/solvers/cc/davidson_cc_es_class.F90
   src/solvers/cc/abstract_cc_es_class.F90
   src/solvers/cc/newton_raphson_cc_gs_class.F90
   src/solvers/cholesky/eri_cd_class.F90
   src/solvers/tdcc/cc_propagation_class.F90
   src/solvers/tdcc/euler_cc_propagation_class.F90
   src/solvers/tdcc/gl2_cc_propagation_class.F90
   src/solvers/tdcc/gl4_cc_propagation_class.F90
   src/solvers/tdcc/gl6_cc_propagation_class.F90
   src/solvers/tdcc/rk4_cc_propagation_class.F90
   src/solvers/tdcc/complex_fft_class.F90
   src/solvers/cc/asymmetric_lanczos_cc_es_class.F90
#
   src/tools/interval_class.F90
   src/tools/index_invert.F90
   src/tools/reordering.F90
   src/tools/timings_class.F90
   src/tools/array_utilities.F90
   src/tools/math_utilities.F90
   src/tools/linked_list/array_list_class.F90
   src/tools/linked_list/array_node_class.F90
   src/tools/fftpack/fftpack_auxiliary_routines.F90
   src/tools/fftpack/fftpack_complex_forward_1d.F90
   src/tools/fftpack/fftpack_complex_initialization_routines.F90
   src/tools/record_storer/record_storer_class.F90
   src/tools/record_storer/memory_storer_class.F90
   src/tools/record_storer/file_storer_class.F90
   src/tools/string_utilities.F90
   src/tools/visualization_class.F90
   src/tools/task_list_class.F90
#
   src/various/butcher_tables.F90
   src/various/continuous_output_coefficients.F90
   src/various/kinds.F90
   src/various/parameters.F90
   src/various/angular_momentum.F90 
#
   src/wavefunctions/wavefunction/wavefunction_class.F90

   src/wavefunctions/hf/frozen_orbital_hf.F90
   src/wavefunctions/hf/hf_class.F90  
   src/wavefunctions/hf/mo_hf.F90
   src/wavefunctions/hf/set_get_hf.F90
   src/wavefunctions/hf/initialize_destruct_hf.F90
   src/wavefunctions/hf/ao_fock_hf.F90
   src/wavefunctions/hf/file_handling_hf.F90
#
   src/wavefunctions/uhf/uhf_class.F90
   src/wavefunctions/uhf/initialize_destruct_uhf.F90
   src/wavefunctions/uhf/set_get_uhf.F90
   src/wavefunctions/uhf/file_handling_uhf.F90
   src/wavefunctions/uhf/ao_fock_uhf.F90
#
   src/wavefunctions/mlhf/mlhf_class.F90
#
   src/wavefunctions/mp2/mp2_class.F90
   src/wavefunctions/mp2/zop_mp2.F90
#
   src/wavefunctions/ccs/ccs_class.F90
   src/wavefunctions/ccs/oei_ccs.F90
   src/wavefunctions/ccs/tei_ccs.F90
   src/wavefunctions/ccs/fock_ccs.F90
   src/wavefunctions/ccs/zop_ccs.F90
   src/wavefunctions/ccs/fop_ccs.F90
   src/wavefunctions/ccs/omega_ccs.F90
   src/wavefunctions/ccs/F_ccs.F90
   src/wavefunctions/ccs/jacobian_ccs.F90
   src/wavefunctions/ccs/jacobian_transpose_ccs.F90
   src/wavefunctions/ccs/multiplier_equation_ccs.F90
   src/wavefunctions/ccs/initialize_destruct_ccs.F90
   src/wavefunctions/ccs/set_get_ccs.F90
   src/wavefunctions/ccs/file_handling_ccs.F90
   src/wavefunctions/ccs/debug_jacobian_ccs.F90
   src/wavefunctions/ccs/t1_ccs.F90
   src/wavefunctions/ccs/complex_ccs.F90
   src/wavefunctions/ccs/autogenerated_complex_files/tei_ccs_complex.F90
   src/wavefunctions/ccs/autogenerated_complex_files/t1_ccs_complex.F90
   src/wavefunctions/ccs/autogenerated_complex_files/fock_ccs_complex.F90
   src/wavefunctions/ccs/autogenerated_complex_files/zop_ccs_complex.F90
   src/wavefunctions/ccs/autogenerated_complex_files/omega_ccs_complex.F90
   src/wavefunctions/ccs/autogenerated_complex_files/jacobian_transpose_ccs_complex.F90
   src/wavefunctions/ccs/autogenerated_complex_files/multiplier_equation_ccs_complex.F90
   src/wavefunctions/ccs/autogenerated_complex_files/set_get_ccs_complex.F90
   src/wavefunctions/ccs/autogenerated_complex_files/initialize_destruct_ccs_complex.F90
#
   src/wavefunctions/doubles/doubles_class.F90
   src/wavefunctions/doubles/omega_doubles.F90
   src/wavefunctions/doubles/jacobian_doubles.F90
   src/wavefunctions/doubles/jacobian_transpose_doubles.F90
   src/wavefunctions/doubles/file_handling_doubles.F90
   src/wavefunctions/doubles/initialize_destruct_doubles.F90
   src/wavefunctions/doubles/zop_doubles.F90
   src/wavefunctions/doubles/fop_doubles.F90
   src/wavefunctions/doubles/complex_doubles.F90
   src/wavefunctions/doubles/autogenerated_complex_files/initialize_destruct_doubles_complex.F90
   src/wavefunctions/doubles/autogenerated_complex_files/jacobian_transpose_doubles_complex.F90
   src/wavefunctions/doubles/autogenerated_complex_files/omega_doubles_complex.F90
   src/wavefunctions/doubles/autogenerated_complex_files/zop_doubles_complex.F90
#
   src/wavefunctions/cc2/cc2_class.F90
   src/wavefunctions/cc2/zop_cc2.F90
   src/wavefunctions/cc2/omega_cc2.F90
   src/wavefunctions/cc2/jacobian_cc2.F90
   src/wavefunctions/cc2/jacobian_transpose_cc2.F90
   src/wavefunctions/cc2/multiplier_equation_cc2.F90
   src/wavefunctions/cc2/initialize_destruct_cc2.F90
   src/wavefunctions/cc2/debug_jacobian_cc2.F90
#
   src/wavefunctions/lowmem_cc2/lowmem_cc2_class.F90
   src/wavefunctions/lowmem_cc2/omega_lowmem_cc2.F90
   src/wavefunctions/lowmem_cc2/jacobian_lowmem_cc2.F90
   src/wavefunctions/lowmem_cc2/jacobian_transpose_lowmem_cc2.F90
   src/wavefunctions/lowmem_cc2/zop_lowmem_cc2.F90
#
   src/wavefunctions/ccsd/ccsd_class.F90
   src/wavefunctions/ccsd/zop_ccsd.F90
   src/wavefunctions/ccsd/omega_ccsd.F90
   src/wavefunctions/ccsd/file_handling_ccsd.F90
   src/wavefunctions/ccsd/initialize_destruct_ccsd.F90
   src/wavefunctions/ccsd/set_get_ccsd.F90
   src/wavefunctions/ccsd/jacobian_ccsd.F90
   src/wavefunctions/ccsd/jacobian_transpose_ccsd.F90
   src/wavefunctions/ccsd/multiplier_equation_ccsd.F90
   src/wavefunctions/ccsd/debug_jacobian_ccsd.F90
   src/wavefunctions/ccsd/complex_ccsd.F90
   src/wavefunctions/ccsd/autogenerated_complex_files/initialize_destruct_ccsd_complex.F90
   src/wavefunctions/ccsd/autogenerated_complex_files/jacobian_transpose_ccsd_complex.F90
   src/wavefunctions/ccsd/autogenerated_complex_files/multiplier_equation_ccsd_complex.F90
   src/wavefunctions/ccsd/autogenerated_complex_files/omega_ccsd_complex.F90
   src/wavefunctions/ccsd/autogenerated_complex_files/set_get_ccsd_complex.F90
   src/wavefunctions/ccsd/autogenerated_complex_files/zop_ccsd_complex.F90
#
   src/wavefunctions/triples/triples_class.F90
#
   src/wavefunctions/ccsdpt/ccsdpt_class.F90
#
   src/wavefunctions/cc3/cc3_class.F90
   src/wavefunctions/cc3/zop_cc3.F90
   src/wavefunctions/cc3/omega_cc3.F90
   src/wavefunctions/cc3/jacobian_cc3.F90
   src/wavefunctions/cc3/prepare_jacobian_transform_cc3.F90
   src/wavefunctions/cc3/jacobian_transpose_cc3.F90
   src/wavefunctions/cc3/abc_batching_cc3.F90
   src/wavefunctions/cc3/multiplier_equation_cc3.F90
   src/wavefunctions/cc3/initialize_destruct_cc3.F90
   src/wavefunctions/cc3/fop_cc3.F90
   src/wavefunctions/cc3/debug_transition_density_cc3.F90
#
   src/wavefunctions/mlcc2/mlcc2_class.F90
   src/wavefunctions/mlcc2/orbitals_mlcc2.F90
   src/wavefunctions/mlcc2/omega_mlcc2.F90
   src/wavefunctions/mlcc2/jacobian_mlcc2.F90
   src/wavefunctions/mlcc2/jacobian_transpose_mlcc2.F90
   src/wavefunctions/mlcc2/initialize_destruct_mlcc2.F90
   src/wavefunctions/mlcc2/debug_jacobian_mlcc2.F90
)
