#
#
#   eT - a coupled cluster program
#   Copyright (C) 2016-2022 the authors of eT
#
#   eT is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   eT is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <https://www.gnu.org/licenses/>.
#
#
set(eT_fortran_sources
   src/eT_program.F90
#
   src/observer_pattern/observer_class.F90
   src/observer_pattern/observable_class.F90
   src/observer_pattern/observer_node_class.F90
   src/observer_pattern/observer_list_class.F90
#
   src/sad/sad_tool_class.F90
#
   src/engines/abstract_engine_class.F90
   src/engines/reference_engine_class.F90
   src/engines/hf_geoopt_engine_class.F90
   src/engines/tdhf_engine_class.F90
   src/engines/gs_engine_class.F90
   src/engines/es_engine_class.F90
   src/engines/mean_value_engine_class.F90
   src/engines/response_engine_class.F90
   src/engines/td_engine_class.F90
#
   src/eri_tool/eri_tool_class.F90
   src/eri_tool/eri_adapter_class.F90
   src/eri_tool/eri_cholesky_disk_class.F90
   src/eri_tool/eri_memory_tool_class.F90
   src/eri_tool/abstract_eri_tool_class.F90
   src/eri_tool/eri_cholesky_memory_class.F90
   src/eri_tool/abstract_eri_cholesky_class.F90
   src/eri_tool/eri_1idx_transformed_tool_class.F90
#
   src/eri_tool/generated_eri_tool/eri_tool_c_class.F90
   src/eri_tool/generated_eri_tool/eri_adapter_c_class.F90
   src/eri_tool/generated_eri_tool/eri_cholesky_disk_c_class.F90
   src/eri_tool/generated_eri_tool/eri_memory_tool_c_class.F90
   src/eri_tool/generated_eri_tool/abstract_eri_tool_c_class.F90
   src/eri_tool/generated_eri_tool/eri_cholesky_memory_c_class.F90
   src/eri_tool/generated_eri_tool/abstract_eri_cholesky_c_class.F90
#
   src/io/abstract_file_class.F90
   src/io/abstract_stream_class.F90
   src/io/abstract_out_file_class.F90
   src/io/direct_stream_file_class.F90
   src/io/sequential_file_class.F90
   src/io/stream_file_class.F90
   src/io/input_file_class.F90
   src/io/section_class.F90
   src/io/output_file_class.F90
   src/io/timings_file_class.F90
   src/io/global_out.F90
   src/io/global_in.F90
#
   src/libint/libint_initialization.F90
#
   src/memory/batching_index_class.F90
   src/memory/memory_manager_class.F90
   src/memory/memory_tracker_class.F90
#
   src/embedding/mm_atom_class.F90
   src/embedding/mm_molecule_class.F90
   src/embedding/environment_factory_class.F90
   src/embedding/environment_class.F90
   src/embedding/electrostatic_environment_class.F90
   src/embedding/fq_environment_class.F90
   src/embedding/pcm_environment_class.F90
#
   src/molecule/atomic_center_class.F90
   src/molecule/atomic_center_reader_class.F90
   src/molecule/ao_tool_class.F90
   src/molecule/periodic_table.F90
   src/molecule/shell_class.F90
   src/molecule/qed_tool_class.F90
   src/molecule/ri_basis_class.F90
#
   src/solver_tools/cholesky_array_list_class.F90
   src/solver_tools/bfgs_tool_class.F90
   src/solver_tools/diis_tool_class.F90
   src/solver_tools/davidson_tool_class.F90
   src/solver_tools/eigen_davidson_tool_class.F90
   src/solver_tools/linear_davidson_tool_class.F90
   src/solver_tools/es_start_vectors/es_start_vector_tool_class.F90
   src/solver_tools/es_start_vectors/es_manual_start_vector_tool_class.F90
   src/solver_tools/es_start_vectors/es_valence_start_vector_tool_class.F90
   src/solver_tools/es_start_vectors/es_cvs_start_vector_tool_class.F90
   src/solver_tools/es_start_vectors/es_ip_start_vector_tool_class.F90
   src/solver_tools/es_projectors/es_projection_tool_class.F90
   src/solver_tools/es_projectors/es_cvs_projection_tool_class.F90
   src/solver_tools/es_projectors/es_rm_core_projection_tool_class.F90
   src/solver_tools/es_projectors/es_valence_projection_tool_class.F90
   src/solver_tools/es_projectors/es_ip_projection_tool_class.F90
#
   src/solver_tools/amplitude_updaters/amplitude_updater_class.F90
   src/solver_tools/amplitude_updaters/quasi_newton_updater_class.F90
   src/solver_tools/amplitude_updaters/newton_raphson_updater_class.F90
   src/solver_tools/amplitude_updaters/abstract_jacobian_transformer_class.F90
   src/solver_tools/amplitude_updaters/approximate_jacobian_transformer_class.F90
   src/solver_tools/amplitude_updaters/jacobian_transformer_class.F90
#
   src/fields/electric_field_class.F90
   src/solver_tools/precondition_tool_class.F90
   src/solver_tools/asymmetric_lanczos_tool_class.F90
   src/solver_tools/convergence_tool_class.F90
#
   src/solver_tools/transformation_tool_class.F90
   src/solver_tools/cc_jacobian_transformation_tool_class.F90
   src/solver_tools/tamm_dancoff_transformation_tool_class.F90
   src/solver_tools/rpa_transformation_tool_class.F90
#
   src/solver_tools/cc_multipliers_solver_factory_class.F90
   src/solver_tools/tdhf_solver_factory_class.F90
   src/solver_tools/scf_solver_factory_class.F90
#
   src/solver_tools/start_vector_tool_class.F90
   src/solver_tools/cc_multipliers_start_vector_tool_class.F90
   src/solver_tools/tdhf_start_vector_tool_class.F90
#
   src/solver_tools/preconditioner_getter_class.F90
   src/solver_tools/cc_multipliers_preconditioner_getter_class.F90
   src/solver_tools/rpa_preconditioner_getter_class.F90
   src/solver_tools/tamm_dancoff_preconditioner_getter_class.F90
#
   src/solver_tools/rhs_linear_equation_tool_class.F90
   src/solver_tools/cc_multipliers_rhs_tool_class.F90
#
   src/solver_tools/eigen_storage_tool_class.F90
   src/solver_tools/tamm_dancoff_eigen_storage_tool_class.F90
   src/solver_tools/rpa_eigen_storage_tool_class.F90
#
   src/solver_tools/linear_storage_tool_class.F90
   src/solver_tools/cc_multipliers_linear_storage_tool_class.F90
#
   src/solver_tools/functions/function_class.F90
   src/solver_tools/functions/hf_energy_function_class.F90
#
   src/solvers/hf/scf_solver_class.F90
   src/solvers/hf/accelerator_tool_class.F90
   src/solvers/hf/accelerator_factory_class.F90
   src/solvers/hf/null_accelerator_tool_class.F90
   src/solvers/hf/diis_accelerator_tool_class.F90
   src/solvers/cc/diis_cc_gs_class.F90
   src/solvers/cc/diis_cc_es_class.F90
   src/solvers/cc/diis_cc_multipliers_class.F90
   src/solvers/cc/davidson_cc_linear_equations_class.F90
   src/solvers/cc/nonlinear_davidson_cc_es_class.F90
   src/solvers/cc/davidson_cc_es_class.F90
   src/solvers/cc/abstract_cc_es_class.F90
   src/solvers/cholesky/eri_cd_class.F90
   src/solvers/cholesky/eri_ri_class.F90
   src/solvers/tdcc/cc_propagation_class.F90
   src/solvers/tdcc/euler_cc_propagation_class.F90
   src/solvers/tdcc/gl2_cc_propagation_class.F90
   src/solvers/tdcc/gl4_cc_propagation_class.F90
   src/solvers/tdcc/gl6_cc_propagation_class.F90
   src/solvers/tdcc/rk4_cc_propagation_class.F90
   src/solvers/tdcc/complex_fft_class.F90
   src/solvers/cc/asymmetric_lanczos_cc_es_class.F90
   src/solvers/bfgs_solver_class.F90
#
   src/solvers/general_eigen_davidson_solver_class.F90
   src/solvers/general_linear_davidson_solver_class.F90
#
   src/tools/index_invert.F90
   src/tools/reordering.F90
   src/tools/rectangular_full_packed_utilities_r.F90
   src/tools/generated_tools/rectangular_full_packed_utilities_c.F90
   src/tools/timings_class.F90
   src/tools/array_utilities.F90
   src/tools/packed_array_utilities_r.F90
   src/tools/generated_tools/packed_array_utilities_c.F90
   src/tools/math_utilities.F90
   src/tools/linked_list/array_list_class.F90
   src/tools/linked_list/array_node_class.F90
   src/tools/linked_list/array_3D_node_class.F90
   src/tools/linked_list/array_3D_list_class.F90
   src/tools/linked_list/generated_linked_list/array_3D_node_c_class.F90
   src/tools/linked_list/generated_linked_list/array_3D_list_c_class.F90
   src/tools/fftpack/fftpack_auxiliary_routines.F90
   src/tools/fftpack/fftpack_complex_forward_1d.F90
   src/tools/fftpack/fftpack_complex_initialization_routines.F90
   src/tools/record_storer_class.F90
   src/tools/string_utilities.F90
   src/tools/visualization_class.F90
   src/tools/task_list_class.F90
   src/tools/z_matrix_tool_class.F90
   src/tools/electrostatics/point_charges_class.F90
   src/tools/electrostatics/point_charge_class.F90
   src/tools/orbitals/cholesky_orbital_tool_class.F90
   src/tools/maps/range_class.F90
   src/tools/maps/named_range_class.F90
   src/tools/maps/block_class.F90
   src/tools/orbitals/nto_tool_class.F90
   src/tools/orbitals/cnto_tool_class.F90
   src/tools/redundant_internal_coords_class.F90
#
   src/tools/citation_printer_class.F90
   src/tools/citation_class.F90
#
   src/various/butcher_tables.F90
   src/various/continuous_output_coefficients.F90
   src/various/kinds.F90
   src/various/parameters.F90
   src/various/warning_suppressor.F90
   src/various/angular_momentum/angular_momentum_factory.F90
   src/various/angular_momentum/abstract_angular_momentum_class.F90
   src/various/angular_momentum/s_angular_momentum.F90
   src/various/angular_momentum/cartesian_p_angular_momentum.F90
   src/various/angular_momentum/cartesian_d_angular_momentum.F90
   src/various/angular_momentum/cartesian_f_angular_momentum.F90
   src/various/angular_momentum/cartesian_g_angular_momentum.F90
   src/various/angular_momentum/cartesian_h_angular_momentum.F90
   src/various/angular_momentum/cartesian_i_angular_momentum.F90
   src/various/angular_momentum/spherical_d_angular_momentum.F90
   src/various/angular_momentum/spherical_f_angular_momentum.F90
   src/various/angular_momentum/spherical_g_angular_momentum.F90
   src/various/angular_momentum/spherical_h_angular_momentum.F90
   src/various/angular_momentum/spherical_i_angular_momentum.F90
#
   src/wavefunctions/wavefunction/wavefunction_class.F90

   src/wavefunctions/hf/frozen_orbital_hf.F90
   src/wavefunctions/hf/hf_class.F90
   src/wavefunctions/hf/set_get_hf.F90
   src/wavefunctions/hf/initialize_destruct_hf.F90
   src/wavefunctions/hf/ao_fock_hf.F90
   src/wavefunctions/hf/file_handling_hf.F90
   src/wavefunctions/hf/tdhf_transformation_hf.F90
#
   src/wavefunctions/cuhf/cuhf_class.F90
#
   src/wavefunctions/rohf/rohf_class.F90
#
   src/wavefunctions/uhf/uhf_class.F90
   src/wavefunctions/uhf/initialize_destruct_uhf.F90
   src/wavefunctions/uhf/set_get_uhf.F90
   src/wavefunctions/uhf/file_handling_uhf.F90
   src/wavefunctions/uhf/ao_fock_uhf.F90
#
   src/wavefunctions/mlhf/mlhf_class.F90
#
   src/wavefunctions/qed_hf/qed_hf_class.F90
#
   src/wavefunctions/mp2/mp2_class.F90
   src/wavefunctions/mp2/mean_value_mp2.F90
#
   src/wavefunctions/ccs/ccs_class.F90
   src/wavefunctions/ccs/oei_ccs.F90
   src/wavefunctions/ccs/fock_ccs.F90
   src/wavefunctions/ccs/mean_value_ccs.F90
   src/wavefunctions/ccs/response_ccs.F90
   src/wavefunctions/ccs/omega_ccs.F90
   src/wavefunctions/ccs/F_ccs.F90
   src/wavefunctions/ccs/jacobian_ccs.F90
   src/wavefunctions/ccs/jacobian_transpose_ccs.F90
   src/wavefunctions/ccs/multiplier_equation_ccs.F90
   src/wavefunctions/ccs/initialize_destruct_ccs.F90
   src/wavefunctions/ccs/set_get_ccs.F90
   src/wavefunctions/ccs/file_handling_ccs.F90
   src/wavefunctions/ccs/t1_ccs.F90
   src/wavefunctions/ccs/complex_ccs.F90
   src/wavefunctions/ccs/generated_complex_files/t1_ccs_complex.F90
   src/wavefunctions/ccs/generated_complex_files/fock_ccs_complex.F90
   src/wavefunctions/ccs/generated_complex_files/mean_value_ccs_complex.F90
   src/wavefunctions/ccs/generated_complex_files/omega_ccs_complex.F90
   src/wavefunctions/ccs/generated_complex_files/jacobian_transpose_ccs_complex.F90
   src/wavefunctions/ccs/generated_complex_files/multiplier_equation_ccs_complex.F90
   src/wavefunctions/ccs/generated_complex_files/set_get_ccs_complex.F90
   src/wavefunctions/ccs/generated_complex_files/initialize_destruct_ccs_complex.F90
#
   src/wavefunctions/doubles/doubles_class.F90
   src/wavefunctions/doubles/omega_doubles.F90
   src/wavefunctions/doubles/jacobian_doubles.F90
   src/wavefunctions/doubles/jacobian_transpose_doubles.F90
   src/wavefunctions/doubles/file_handling_doubles.F90
   src/wavefunctions/doubles/initialize_destruct_doubles.F90
   src/wavefunctions/doubles/mean_value_doubles.F90
   src/wavefunctions/doubles/response_doubles.F90
   src/wavefunctions/doubles/complex_doubles.F90
   src/wavefunctions/doubles/generated_complex_files/initialize_destruct_doubles_complex.F90
   src/wavefunctions/doubles/generated_complex_files/jacobian_transpose_doubles_complex.F90
   src/wavefunctions/doubles/generated_complex_files/omega_doubles_complex.F90
   src/wavefunctions/doubles/generated_complex_files/mean_value_doubles_complex.F90
#
   src/wavefunctions/cc2/cc2_class.F90
   src/wavefunctions/cc2/mean_value_cc2.F90
   src/wavefunctions/cc2/omega_cc2.F90
   src/wavefunctions/cc2/jacobian_cc2.F90
   src/wavefunctions/cc2/jacobian_transpose_cc2.F90
   src/wavefunctions/cc2/multiplier_equation_cc2.F90
   src/wavefunctions/cc2/initialize_destruct_cc2.F90
   src/wavefunctions/cc2/fock_cc2.F90
#
   src/wavefunctions/lowmem_cc2/lowmem_cc2_class.F90
   src/wavefunctions/lowmem_cc2/omega_lowmem_cc2.F90
   src/wavefunctions/lowmem_cc2/jacobian_lowmem_cc2.F90
   src/wavefunctions/lowmem_cc2/jacobian_transpose_lowmem_cc2.F90
   src/wavefunctions/lowmem_cc2/mean_value_lowmem_cc2.F90
   src/wavefunctions/lowmem_cc2/fock_lowmem_cc2.F90
#
   src/wavefunctions/ccsd/ccsd_class.F90
   src/wavefunctions/ccsd/mean_value_ccsd.F90
   src/wavefunctions/ccsd/omega_ccsd.F90
   src/wavefunctions/ccsd/file_handling_ccsd.F90
   src/wavefunctions/ccsd/initialize_destruct_ccsd.F90
   src/wavefunctions/ccsd/set_get_ccsd.F90
   src/wavefunctions/ccsd/jacobian_ccsd.F90
   src/wavefunctions/ccsd/jacobian_transpose_ccsd.F90
   src/wavefunctions/ccsd/multiplier_equation_ccsd.F90
   src/wavefunctions/ccsd/fock_ccsd.F90
   src/wavefunctions/ccsd/F_ccsd.F90
   src/wavefunctions/ccsd/complex_ccsd.F90
   src/wavefunctions/ccsd/generated_complex_files/initialize_destruct_ccsd_complex.F90
   src/wavefunctions/ccsd/generated_complex_files/jacobian_transpose_ccsd_complex.F90
   src/wavefunctions/ccsd/generated_complex_files/multiplier_equation_ccsd_complex.F90
   src/wavefunctions/ccsd/generated_complex_files/omega_ccsd_complex.F90
   src/wavefunctions/ccsd/generated_complex_files/set_get_ccsd_complex.F90
   src/wavefunctions/ccsd/generated_complex_files/mean_value_ccsd_complex.F90
   src/wavefunctions/ccsd/generated_complex_files/fock_ccsd_complex.F90
#
   src/wavefunctions/triples/triples_class.F90
#
   src/wavefunctions/ccsdpt/ccsdpt_class.F90
#
   src/wavefunctions/cc3/cc3_class.F90
   src/wavefunctions/cc3/mean_value_cc3.F90
   src/wavefunctions/cc3/omega_cc3.F90
   src/wavefunctions/cc3/jacobian_cc3.F90
   src/wavefunctions/cc3/prepare_jacobian_transform_cc3.F90
   src/wavefunctions/cc3/jacobian_transpose_cc3.F90
   src/wavefunctions/cc3/abc_batching_cc3.F90
   src/wavefunctions/cc3/multiplier_equation_cc3.F90
   src/wavefunctions/cc3/initialize_destruct_cc3.F90
   src/wavefunctions/cc3/response_cc3.F90
#
   src/wavefunctions/mlcc2/mlcc2_class.F90
   src/wavefunctions/mlcc2/orbitals_mlcc2.F90
   src/wavefunctions/mlcc2/file_handling_mlcc2.F90
   src/wavefunctions/mlcc2/omega_mlcc2.F90
   src/wavefunctions/mlcc2/jacobian_mlcc2.F90
   src/wavefunctions/mlcc2/jacobian_transpose_mlcc2.F90
   src/wavefunctions/mlcc2/initialize_destruct_mlcc2.F90
   src/wavefunctions/mlcc2/fock_mlcc2.F90
   src/wavefunctions/mlcc2/file_handling_mlcc2.F90
#
   src/wavefunctions/mlccsd/mlccsd_class.F90
   src/wavefunctions/mlccsd/orbitals_mlccsd.F90
   src/wavefunctions/mlccsd/omega_mlccsd.F90
   src/wavefunctions/mlccsd/initialize_destruct_mlccsd.F90
   src/wavefunctions/mlccsd/file_handling_mlccsd.F90
   src/wavefunctions/mlccsd/set_get_mlccsd.F90
   src/wavefunctions/mlccsd/jacobian_mlccsd.F90
   src/wavefunctions/mlccsd/fock_mlccsd.F90
)
