#
#
#   eT - a coupled cluster program
#   Copyright (C) 2016-2021 the authors of eT
#
#   eT is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   eT is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#   GNU General Public License for more details.
#
#   You should have received a copy of the GNU General Public License
#   along with this program. If not, see <https://www.gnu.org/licenses/>.
#
# 	Based on the cmake/DaltonTests.cmake file of the public
#   Dalton program (LGPL v2.1)
#
# 	Copied and modified for eT by Rolf H. Myhre, Feb 2019
#
macro(add_eT_runtest _name _labels)

    add_test(
        ${_name}
        python3 ${PROJECT_BINARY_DIR}/tests/${_name}/test --binary-dir=${PROJECT_BINARY_DIR} --work-dir=${PROJECT_BINARY_DIR}/tests/${_name} --verbose)
   
    # add "integration-test" as a label for all integration tests
    string(CONCAT labels "${_labels}" "; integration-test")
    
    set_tests_properties(${_name} PROPERTIES LABELS "${labels}")
    
endmacro()

# All tests here should contain the label "eT"

# Add a keyword for the length of the test:
#
# 	short < 30 seconds
# 	medium > 30 seconds < 120 seconds
# 	long > 120 seconds < 200 seconds
# 	verylong > 200 seconds
#
# NEVER comment out tests
add_eT_runtest(eri_cholesky                                 "eT;short;cholesky;eri")
#
add_eT_runtest(hf_energy                                    "eT;short;hf;sad")
add_eT_runtest(hf_energy_pure_321g                          "eT;short;hf;sad;pople;spherical;molden")
add_eT_runtest(hf_print_z_matrix                            "eT;short;hf;z-matrix")
add_eT_runtest(hf_file_check                                "eT;short;hf;sad;eT_launch")
add_eT_runtest(hf_orbital_files                             "eT;short;hf;sad;eT_launch;molden")
add_eT_runtest(hf_low_memory                                "eT;short;hf;sad")
add_eT_runtest(hf_energy_cumulative                         "eT;short;hf;cumulative-fock")
add_eT_runtest(hf_energy_sto3g                              "eT;short;hf;sad;sto3g")
add_eT_runtest(hf_energy_3-21g                              "eT;short;hf;sad;pople")
add_eT_runtest(hf_energy_6-31g                              "eT;short;hf;sad;pople")
add_eT_runtest(hf_energy_6-31g_pol                          "eT;short;hf;sad;pople;cartesian")
add_eT_runtest(hf_energy_cartesian_basis_set                "eT;short;hf;sad;cartesian")
add_eT_runtest(hf_energy_external_basis                     "eT;short;hf;sad;cartesian;externalbasis")
add_eT_runtest(hf_energy_ghost                              "eT;short;hf;sad")
add_eT_runtest(hf_geoopt                                    "eT;short;hf;bfgs;gradient")
add_eT_runtest(hf_scf_energy                                "eT;short;hf;sad")
add_eT_runtest(hf_energy_qmmmnopol                          "eT;short;hf;sad;qmmm;mmnopol")
add_eT_runtest(hf_energy_qmfq                               "eT;short;hf;sad;qmmm;fq")
add_eT_runtest(hf_scf_energy_qmmmnopol                      "eT;short;hf;sad;qmmm;mmnopol")
add_eT_runtest(hf_scf_energy_qmfq                           "eT;short;hf;sad;qmmm;fq")
add_eT_runtest(hf_dipole                                    "eT;short;hf;sad;dipole")
add_eT_runtest(hf_quadrupole                                "eT;short;hf;sad;quadrupole")
add_eT_runtest(hf_anion                                     "eT;short;hf;sad;charged")
add_eT_runtest(hf_hydroxyl                                  "eT;short;hf;sad;charged")
add_eT_runtest(hf_hydroxyl_charge_sad                       "eT;short;hf;sad;charged")
add_eT_runtest(hf_oxonium_charge_sad                        "eT;short;hf;sad;charged")
add_eT_runtest(restart_hf                                   "eT;short;hf;restart")
#
add_eT_runtest(hf_visualization                             "eT;short;hf;visualization")
add_eT_runtest(plot_benzene_mos                             "eT;short;hf;visualization")
add_eT_runtest(plot_ntos_ccs                                "eT;short;ccs;visualization")
add_eT_runtest(plot_ntos_ccsd                               "eT;short;ccsd;visualization")
add_eT_runtest(plot_cntos_ccsd                              "eT;short;ccsd;visualization")
#
add_eT_runtest(restart_geoopt                               "eT;short;hf;bfgs;gradient,restart")
add_eT_runtest(hf_bohr_units                                "eT;short;hf;sad")
add_eT_runtest(hf_pure_basis                                "eT;short;hf;spherical;pople")
#
add_eT_runtest(tdhf_tamm_dancoff_es                         "eT;short;tdhf;tamm-dancoff")
add_eT_runtest(tdhf_rpa_es                                  "eT;short;tdhf;rpa")
add_eT_runtest(tdhf_restart                                 "eT;short;tdhf;rpa;restart")
add_eT_runtest(tdhf_global_restart                          "eT;short;tdhf;rpa;restart")
#
add_eT_runtest(uhf_energy                                   "eT;short;uhf")
add_eT_runtest(uhf_energy_cs                                "eT;short;uhf;atom")
add_eT_runtest(uhf_energy_qmmmnopol                         "eT;short;uhf;sad;qmmm;mmnopol")
add_eT_runtest(uhf_energy_qmfq                              "eT;short;uhf;sad;qmmm;fq")
add_eT_runtest(uhf_dipole                                   "eT;short;uhf;sad;dipole")
add_eT_runtest(uhf_atomic_doublet                           "eT;short;uhf;spin")
add_eT_runtest(uhf_molecular_triplet                        "eT;short;uhf;spin")
add_eT_runtest(uhf_file_check                               "eT;short;uhf;spin;eT_launch")
add_eT_runtest(restart_uhf                                  "eT;short;uhf;spin")
add_eT_runtest(restart_uhf_v1.0                             "eT;short;uhf;spin;v1.0")
#
add_eT_runtest(mlhf_cholesky_energy                         "eT;short;mlhf;sad;cholesky")
add_eT_runtest(mlhf_pao_energy                              "eT;short;mlhf;sad;pao")
add_eT_runtest(mlhf_pao_energy_central_atom                 "eT;short;mlhf;sad;pao;central-atom")
add_eT_runtest(mlhf_scf_energy                              "eT;short;mlhf;sad;pao")
add_eT_runtest(mlhf_full_space_energy                       "eT;short;mlhf;sad;pao")
add_eT_runtest(mlhf_min_basis_diagonalization_energy        "eT;short;mlhf;sad;pao")
add_eT_runtest(mlhf_initial_full_space_optimization         "eT;short;mlhf;sad;pao")
add_eT_runtest(mlhf_dipole                                  "eT;short;mlhf;dipole")
add_eT_runtest(mlhf_quadrupole                              "eT;short;mlhf;quadrupole")
add_eT_runtest(restart_mlhf                                 "eT;short;mlhf;sad;pao;restart")
add_eT_runtest(mlhf_active_inactive_basis                   "eT;short;mlhf;basis")
#
add_eT_runtest(mp2_energy                                   "eT;short;hf;mp2")
add_eT_runtest(mp2_energy_qmmmnopol                         "eT;short;hf;mp2;qmmm;mmnopol")
add_eT_runtest(mp2_energy_qmfq                              "eT;short;hf;mp2;qmmm;fq")
#
add_eT_runtest(ccs_frozen_core                              "eT;short;ccs;gs;es;frozen core")
add_eT_runtest(ccs_lr_polarizability_transition_moments     "eT;short;ccs;es;lr")
add_eT_runtest(ccs_oscillator_strength_eom                  "eT;short;ccs;es;eom")
add_eT_runtest(ccs_eom_diis_parallel_states                 "eT;short;ccs;es;eom;diis;parallel states")
add_eT_runtest(ccs_td_rk4                                   "eT;short;ccs;complex;td")
add_eT_runtest(ccs_right_lt_lindep                          "eT;short;ccs;es")
add_eT_runtest(ccs_es_remove_core                           "eT;short;ccs;es")
add_eT_runtest(ccs_right_ip_energies                        "eT;short;ccs;ip;right")
add_eT_runtest(restart_ccs_es                               "eT;short;ccs;es;restart")
add_eT_runtest(restart_ccs_gs_dipole                        "eT;short;ccs;gs;dipole;restart")
add_eT_runtest(restart_ccs_eom                              "eT;short;ccs;eom;restart")
add_eT_runtest(restart_ccs_from_ccsd                        "eT;short;ccs;eom;es;restart")
add_eT_runtest(restart_ccs_v1.0                             "eT;short;ccs;eom;restart;v1.0")
#
add_eT_runtest(cc2_gs_energy                                "eT;short;cc2;gs")
add_eT_runtest(cc2_gs_MO_screening                          "eT;short;cc2;gs;cholesky;mo screening")
add_eT_runtest(cc2_gs_energy_cholesky_on_file               "eT;short;cc2;gs;cholesky-storage")
add_eT_runtest(cc2_gs_energy_batched_cd                     "eT;short;cc2;gs;pcd")
add_eT_runtest(cc2_dipole                                   "eT;short;cc2;gs;dipole")
add_eT_runtest(cc2_frozen_core                              "eT;short;cc2;gs;es;frozen core")
add_eT_runtest(cc2_right_es_energies                        "eT;short;cc2;es;right")
add_eT_runtest(cc2_right_es_energies_diis                   "eT;short;cc2;es;right;diis")
add_eT_runtest(cc2_right_cvs_es_energies                    "eT;short;cc2;es;right;cvs")
add_eT_runtest(cc2_right_cvs_es_energies_diis               "eT;short;cc2;es;right;cvs;diis")
add_eT_runtest(cc2_right_ip_energies                        "eT;short;cc2;es;right")
add_eT_runtest(cc2_right_ip_diis                            "eT;short;cc2;es;right;diis")
add_eT_runtest(cc2_left_es_energies                         "eT;short;cc2;es;left")
add_eT_runtest(cc2_left_right_es_energies                   "eT;short;cc2;es;left;right")
add_eT_runtest(cc2_left_cvs_es_energies                     "eT;short;cc2;es;left;cvs")
add_eT_runtest(cc2_left_ip_energies                         "eT;short;cc2;es;left")
add_eT_runtest(cc2_left_ip_diis                             "eT;short;cc2;es;left;diis")
add_eT_runtest(cc2_oscillator_strength_eom                  "eT;short;cc2;eom")
add_eT_runtest(cc2_eom_polarizability                       "eT;short;cc2;es;eom")
add_eT_runtest(cc2_frozen_hf_many_basis_sets                "eT;short;cc2;gs;frozen hf;many basis sets")
add_eT_runtest(restart_cc2_es                               "eT;short;cc2;es;restart")
add_eT_runtest(cc2_lowmem_gs_energy                         "eT;short;lowmem-cc2;gs")
add_eT_runtest(cc2_lowmem_frozen_core                       "eT;short;lowmem-cc2;es;gs;frozen core")
add_eT_runtest(cc2_lowmem_right_es_energies                 "eT;short;lowmem-cc2;es;right")
add_eT_runtest(cc2_lowmem_left_es_energies                  "eT;short;lowmem-cc2;es")
add_eT_runtest(cc2_lowmem_right_nonlin_davidson             "eT;short;lowmem-cc2;es;non-linear davidson")
add_eT_runtest(cc2_lowmem_right_diis_w_davidson_preconv     "eT;short;lowmem-cc2;es;diis;non-linear davidson")
add_eT_runtest(restart_lowmem_cc2_es                        "eT;short;lowmem-cc2;es;restart")
add_eT_runtest(restart_cc2_lowmem_from_ccs                  "eT;short;lowmem-cc2;es;restart")
add_eT_runtest(restart_cc2_v1.0                             "eT;short;cc2;es;restart;v1.0")
#
add_eT_runtest(ccsd_gs_energy                               "eT;short;ccsd;gs")
add_eT_runtest(ccsd_frozen_hf_gs_energy                     "eT;short;ccsd;gs;frozen hf")
add_eT_runtest(ccsd_frozen_hf_frozen_core_gs_energy         "eT;short;ccsd;gs;frozen hf; frozen core")
add_eT_runtest(ccsd_gs_energy_qmmmnopol                     "eT;short;ccsd;gs;qmmm;mmnopol")
add_eT_runtest(ccsd_gs_energy_qmfq                          "eT;short;ccsd;gs;qmmm;fq")
add_eT_runtest(ccsd_gs_energy_1c_cd                         "eT;short;ccsd;gs;1c-cd")
add_eT_runtest(ccsd_dipole                                  "eT;short;ccsd;gs;dipole")
add_eT_runtest(ccsd_dipole_fc                               "eT;short;ccsd;gs;dipole;frozen core")
add_eT_runtest(ccsd_quadrupole                              "eT;short;ccsd;gs;quadrupole")
add_eT_runtest(ccsd_quadrupole_fc                           "eT;short;ccsd;gs;quadrupole;frozen core")
add_eT_runtest(ccsd_frozen_core                             "eT;short;ccsd;es;gs;frozen core")
add_eT_runtest(ccsd_frozen_core_xenon                       "eT;short;ccsd;es;gs;frozen core;atom")
add_eT_runtest(ccsd_right_es_energies                       "eT;short;ccsd;es;right")
add_eT_runtest(ccsd_right_es_energies_imaginary             "eT;medium;ccsd;es;right;davidson;imaginary-pair")
add_eT_runtest(ccsd_es_false_positive_defect                "eT;medium;ccsd;es;right;davidson;imaginary-pair")
add_eT_runtest(ccsd_right_es_replace_red_space              "eT;short;ccsd;es;right;red_space")
add_eT_runtest(ccsd_right_es_diis                           "eT;short;ccsd;es;right;diis")
add_eT_runtest(ccsd_right_cvs_es_energies                   "eT;short;ccsd;es;right;cvs")
add_eT_runtest(ccsd_right_cvs_ccX-dz                        "eT;short;ccsd;es;right;cvs;ccX-dz")
add_eT_runtest(ccsd_right_cvs_es_energies_diis              "eT;short;ccsd;es;right;cvs;diis")
add_eT_runtest(ccsd_right_ip_energies                       "eT;short;ccsd;ip;right")
add_eT_runtest(ccsd_right_ip_diis                           "eT;short;ccsd;ip;right;diis")
add_eT_runtest(ccsd_right_es_energies_cartgauss             "eT;short;ccsd;es;right;cartesian gaussians")
add_eT_runtest(ccsd_es_remove_core                          "eT;short;ccsd;es;remove-core")
add_eT_runtest(ccsd_left_ip_energies                        "eT;short;ccsd;ip;left")
add_eT_runtest(ccsd_left_ip_diis                            "eT;short;ccsd;ip;left;diis")
add_eT_runtest(ccsd_left_es_energies                        "eT;short;ccsd;es;left")
add_eT_runtest(ccsd_left_es_diis                            "eT;short;ccsd;es;left;diis")
add_eT_runtest(ccsd_es_lanczos                              "eT;short;ccsd;es;eom;lanczos")
add_eT_runtest(ccsd_cvs_lanczos                             "eT;short;ccsd;es;eom;lanczos;cvs")
add_eT_runtest(ccsd_eom_polarizability                      "eT;short;ccsd;es;eom")
add_eT_runtest(ccsd_lr_polarizability_transition_moments_nosym "eT;short;ccsd;es;eom")
add_eT_runtest(ccsd_lr_polarizability_transition_moments       "eT;short;ccsd;es;eom")
add_eT_runtest(ccsd_oscillator_strength_eom                 "eT;short;ccsd;es;eom")
add_eT_runtest(ccsd_oscillator_strength_eom_crop            "eT;short;ccsd;es;eom;crop")
add_eT_runtest(ccsd_oscillator_strength_eom_records_in_mem  "eT;short;ccsd;es;eom")
add_eT_runtest(ccsd_es_transition_strengths                 "eT;short;ccsd;es;eom")
add_eT_runtest(ccsd_es_dipole_moments                       "eT;short;ccsd;es;eom;dipole")
add_eT_runtest(ccsd_es_cvs_properties                       "eT;short;ccsd;es;eom;cvs;dipole")
add_eT_runtest(ccsd_cvs_eom_degeneracy                      "eT;short;ccsd;es;eom;diis;degeneracy")
add_eT_runtest(ccsd_td_rk4                                  "eT;short;ccsd;complex;td")
add_eT_runtest(ccsd_td_rk4_train                            "eT;short;ccsd;complex;td")
add_eT_runtest(ccsd_td_rk4_many_pulses                      "eT;short;ccsd;complex;td")
add_eT_runtest(ccsd_td_euler                                "eT;short;ccsd;complex;td")
add_eT_runtest(ccsd_td_euler_fft                            "eT;short;ccsd;complex;td")
add_eT_runtest(ccsd_td_gl2                                  "eT;short;ccsd;complex;td")
add_eT_runtest(ccsd_td_gl2_gaussian_envelope                "eT;short;ccsd;complex;td")
add_eT_runtest(ccsd_td_gl4                                  "eT;short;ccsd;complex;td")
add_eT_runtest(ccsd_td_gl6                                  "eT;short;ccsd;complex;td")
add_eT_runtest(ri_ccsd                                      "eT;short;ccsd;ri")
add_eT_runtest(restart_ccsd_es                              "eT;short;ccsd;es;restart")
add_eT_runtest(restart_ccsd_eom                             "eT;short;ccsd;eom;restart")
add_eT_runtest(restart_ccsd_eom_from_left                   "eT;short;ccsd;eom;restart")
add_eT_runtest(restart_ccsd_2_states_from_1                 "eT;short;ccsd;eom;restart")
add_eT_runtest(restart_ccsd_from_ccs                        "eT;short;ccsd;eom;es;restart")
add_eT_runtest(restart_ccsd_right_from_left                 "eT;short;ccsd;es;restart")
add_eT_runtest(restart_ccsd_left_from_right                 "eT;short;ccsd;es;restart")
add_eT_runtest(restart_ccsd_eom_diis                        "eT;short;ccsd;eom;restart")
add_eT_runtest(restart_right_ccsd_oscillator_strength_eom   "eT;short;ccsd;es;eom;restart")
add_eT_runtest(restart_ccsd_v1.0                            "eT;short;ccsd;eom;restart;v1.0")
add_eT_runtest(restart_ccsd_from_cc2_v1.0                   "eT;short;ccsd;eom;restart;v1.0")
#
add_eT_runtest(mlhf_ccsd_gs_energy                          "eT;short;mlhf;ccsd;pao")
add_eT_runtest(mlhf_frozen_hf_ccsd_gs_energy                "eT;short;mlhf;ccsd;pao;frozen core")
add_eT_runtest(mlhf_fc_ccsd_gs_energy                       "eT;short;mlhf;ccsd;pao;frozen hf")
#
add_eT_runtest(ccsdpt_gs_energy                             "eT;short;ccsdpt;gs")
#
add_eT_runtest(cc3_gs_energy                                "eT;short;cc3;gs")
add_eT_runtest(cc3_dipole                                   "eT;short;cc3;gs;dipole")
add_eT_runtest(cc3_frozen_core                              "eT;short;cc3;gs;es;frozen core")
add_eT_runtest(cc3_right_es_energies                        "eT;short;cc3;es;right;diis")
add_eT_runtest(cc3_right_cvs_es_energies                    "eT;short;cc3;es;right;cvs;diis")
add_eT_runtest(cc3_cvs_right_diis_w_davidson_preconv        "eT;short;cc3;es;right;cvs;diis;non-linear davidson")
add_eT_runtest(cc3_left_es_energies                         "eT;short;cc3;es;left;diis")
add_eT_runtest(cc3_left_cvs_es_energies                     "eT;short;cc3;es;left;cvs;diis")
add_eT_runtest(cc3_oscillator_strength_eom                  "eT;short;cc3;es;eom")
add_eT_runtest(cc3_oscillator_strength_eom_cvs              "eT;short;cc3;es;eom;cvs")
add_eT_runtest(cc3_es_properties                            "eT;short;cc3;es;eom")
add_eT_runtest(cc3_es_cvs_properties                        "eT;short;cc3;es;eom;cvs")
add_eT_runtest(cc3_es_remove-core_properties                "eT;short;cc3;es;eom;remove-core")
add_eT_runtest(cc3_visualization                            "eT;short;cc3;visualization;es;eom")
add_eT_runtest(restart_cc3_from_ccsd                        "eT;short;cc3;es;eom;restart")
#
add_eT_runtest(mlcc2_cnto_full_right_es                     "eT;short;mlcc2;es;cnto")
add_eT_runtest(mlcc2_pao_full_right_es                      "eT;short;mlcc2;es;pao")
add_eT_runtest(mlcc2_pao_right_es                           "eT;short;mlcc2;es;pao")
add_eT_runtest(mlcc2_pao_right_es_fc                        "eT;short;mlcc2;es;pao;fc")
add_eT_runtest(mlcc2_pao_right_es_frozen_hf                 "eT;short;mlcc2;es;pao;frozen-hf")
add_eT_runtest(mlcc2_pao_mlhf_gs                            "eT;short;mlcc2;gs;pao;mlhf")
add_eT_runtest(mlcc2_pao_left_es                            "eT;short;mlcc2;es;pao")
add_eT_runtest(mlcc2_nto_full_right_es                      "eT;short;mlcc2;es;nto")
add_eT_runtest(mlcc2_nto_right_es                           "eT;short;mlcc2;es;nto")
add_eT_runtest(mlcc2_nto_left_es                            "eT;short;mlcc2;es;nto")
add_eT_runtest(mlcc2_cholesky_full_right_es                 "eT;short;mlcc2;es;cholesky")
add_eT_runtest(mlcc2_cholesky_right_es                      "eT;short;mlcc2;es;cholesky")
add_eT_runtest(mlcc2_cholesky_full_left_es                  "eT;short;mlcc2;es;cholesky")
add_eT_runtest(mlcc2_cholesky_full_right_cvs_es             "eT;short;mlcc2;es;cholesky;cvs")
add_eT_runtest(mlcc2_cholesky_full_left_cvs_es              "eT;short;mlcc2;es;cholesky;cvs")
add_eT_runtest(mlcc2_cholesky_right_cvs_es                  "eT;short;mlcc2;es;cholesky;cvs")
add_eT_runtest(mlcc2_cnto_right_es                          "eT;short;mlcc2;es;cnto")
add_eT_runtest(mlcc2_cnto_left_es                           "eT;short;mlcc2;es;cnto")
add_eT_runtest(mlcc2_full_fc_es                             "eT;short;mlcc2;es;cholesky;frozen core")
add_eT_runtest(mlcc2_fc_es                                  "eT;short;mlcc2;es;cnto;frozen core")
add_eT_runtest(restart_mlcc2_cholesky_es                    "eT;short;mlcc2;es;cholesky;restart")
add_eT_runtest(restart_mlcc2_left_from_right                "eT;short;mlcc2;es;cholesky;restart")
add_eT_runtest(restart_mlcc2_right_from_left                "eT;short;mlcc2;es;cholesky;restart")
add_eT_runtest(restart_mlcc2_cnto_es                        "eT;short;mlcc2;es;cnto;restart")
add_eT_runtest(restart_mlcc2_nto                            "eT;short;mlcc2;es;nto;restart")
add_eT_runtest(restart_orbitals_mlcc2_cholesky_pao          "eT;short;mlcc2;es;cholesky-pao;restart")
#
add_eT_runtest(mlccsd_cnto_full_gs                          "eT;short;mlccsd;gs;cnto")
add_eT_runtest(mlccsd_cnto_gs                               "eT;short;mlccsd;gs;cnto")
add_eT_runtest(mlccsd_cnto_mlhf_gs                          "eT;short;mlccsd;mlhf;gs;cnto")
add_eT_runtest(mlccsd_pao_gs                                "eT;short;mlccsd;gs;pao")
add_eT_runtest(mlccsd_cc2_cnto_gs                           "eT;short;mlccsd;gs;cnto")
add_eT_runtest(mlccsd_nto_gs                                "eT;short;mlccsd;gs;nto")
add_eT_runtest(mlccsd_cnto_full_es                          "eT;short;mlccsd;es;cnto")
add_eT_runtest(mlccsd_cnto_es                               "eT;short;mlccsd;es;cnto")
add_eT_runtest(mlccsd_pao_es                                "eT;short;mlccsd;es;pao")
add_eT_runtest(mlccsd_pao_full_cvs                          "eT;short;mlccsd;es;pao")
add_eT_runtest(mlccsd_pao_cvs                               "eT;short;mlccsd;es;pao")
add_eT_runtest(restart_mlccsd_cholesky_pao_es               "eT;short;mlccsd;es;cholesky-pao;restart")
add_eT_runtest(restart_orbitals_mlccsd_cholesky_pao         "eT;short;mlccsd;es;cholesky-pao;restart")
add_eT_runtest(restart_orbitals_mlccsd_cc2_cholesky_pao     "eT;short;mlccsd;es;cholesky-pao;restart")
#
if(ENABLE_PCMSOLVER)
   add_eT_runtest(hf_energy_pcm                             "eT;short;hf;sad;pcm;pcm_internal")
   add_eT_runtest(hf_energy_pcm_external                    "eT;short;hf;sad;pcm;pcm_external")
   add_eT_runtest(uhf_energy_pcm                            "eT;short;uhf;sad;pcm;pcm_internal")
   add_eT_runtest(uhf_energy_pcm_external                   "eT;short;uhf;sad;pcm;pcm_external")
   add_eT_runtest(ccsd_gs_energy_pcm                        "eT;short;ccsd;gs;pcm;pcm_internal")
   add_eT_runtest(ccsd_gs_energy_pcm_external               "eT;short;ccsd;gs;pcm;pcm_external")
endif()
#
if (NOT ENABLE_FORCED_BATCHING)
   add_eT_runtest(cc2_lowmem_gs_energy_nr                   "eT;short;lowmem-cc2;gs;newton-raphson")
   add_eT_runtest(cc2_lowmem_gs_energy_multimodel_nr        "eT;short;lowmem-cc2;gs;newton-raphson;multimodel")
   add_eT_runtest(ccsd_gs_energy_nr_crop                    "eT;short;ccsd;newton-raphson;crop")
   add_eT_runtest(ccsd_gs_energy_nr                         "eT;short;ccsd;gs;newton-raphson")
   add_eT_runtest(ccsd_gs_energy_nr_storage                 "eT;short;ccsd;gs;newton-raphson")
   add_eT_runtest(cc3_gs_energy_nr                          "eT;short;cc3;gs;newton-raphson")
   add_eT_runtest(cc3_gs_energy_multimodel_nr               "eT;short;cc3;gs;newton-raphson;multimodel")
   add_eT_runtest(cc3_dipole_nr                             "eT;short;cc3;gs;newton-raphson;dipole")
endif()
