#!/usr/bin/env python3

from pathlib import Path
import sys

# we make sure we can import runtest and runtest_config
sys.path.append(str(Path(__file__).parents[1]))

# we import essential functions from the runtest library
from runtest import version_info, cli, run

# this tells runtest how to run your code
from runtest_config import configure

# functions to get the filters
from filters import get_td_filter, get_file_filter

# we stop the script if the major version is not compatible
assert version_info.major == 2

# construct filter(s)
threshold = 1.0e-9

f = get_td_filter(threshold)
g = get_file_filter(threshold)
filters = {
    'out' : f,
    'cc_propagation_dipole_moment.out' : g,
    'cc_propagation_energy.out' : g,
    'complex_fft.cc_propagation_dipole_moment.out' : g,
    'complex_fft.cc_propagation_electric_field.out' : g,
    }

# invoke the command line interface parser which returns options
options = cli()

ierr = 0
inp = 'ccsd_td_euler_fft.inp'
# the run function runs the code and filters the outputs
ierr += run(options,
            configure,
            input_files=inp,
            filters=filters)
sys.exit(ierr)
