#!/usr/bin/env python3

from pathlib import Path
import sys

# we make sure we can import runtest and runtest_config
sys.path.append(str(Path(__file__).parents[1]))

# we import essential functions from the runtest library
from runtest import version_info, cli, run

# this tells runtest how to run your code
from runtest_config import configure

# we stop the script if the major version is not compatible
assert version_info.major == 2

# functions to get the filters
from filters import get_gs_filter

# construct filter(s)
threshold = 1.0e-10
convergence = True
Newton = True
restart = False

f = get_gs_filter(threshold, convergence, restart, Newton)

# invoke the command line interface parser which returns options
options = cli()

ierr = 0
inp = 'cc3_gs_energy_nr.inp'
# the run function runs the code and filters the outputs
ierr += run(options,
            configure,
            input_files=inp,
            filters={'out': f})

sys.exit(ierr)
