#!/usr/bin/env python3

from pathlib import Path
import sys

# we make sure we can import runtest and runtest_config
sys.path.append(str(Path(__file__).parents[1]))

# we import essential functions from the runtest library
from runtest import version_info, cli, run

# this tells runtest how to run your code
from runtest_config import configure

# functions to get the filters
from filters import get_file_filter, get_es_filter

# we stop the script if the major version is not compatible
assert version_info.major == 2

# construct filter(s)
f = get_es_filter(1, 1.0e-10)
g = get_file_filter(1.0e-9)

filters = {
    'out' : f,
    'CC_MO_0001.cube' : g,
    'CC_MO_0002.cube' : g,
    'mo_information.out' : g,
    'nonfrozen_mo_information.out' : g,
    'mlccsd_mo_information.out' : g,
}

# invoke the command line interface parser which returns options
options = cli()

ierr = 0
inp = 'plot_orbitals_mlccsd_cnto_es.inp'
# the run function runs the code and filters the outputs
ierr += run(options,
            configure,
            input_files=inp,
            filters=filters)

sys.exit(ierr)
